Repository sugarbrain/microhangry, pull requests merged in 2019-06, with the labels that each got.

#5 [CORE-API] Create npm script to run Typeorm with ts-node by default
  core-api/ormconfig.json
  core-api/package.json
  core-api/src/config/database.config.ts
  docker-compose.yml
Labels: feature, infra, migration

#6 [CORE-API] Create User entity, User and Auth routes, controllers and services
  core-api/ormconfig.json
  core-api/package-lock.json
  core-api/package.json
  core-api/src/app.ts
  core-api/src/config/database.ts
  core-api/src/controllers/auth.controller.ts
  core-api/src/controllers/user.controller.ts
  core-api/src/database/migration/1560050558834-UserEntity.ts
  core-api/src/entities/user.entity.ts
  core-api/src/routes/auth.route.ts
  core-api/src/routes/user.route.ts
  core-api/src/services/auth.service.ts
  core-api/src/services/user.service.ts
  core-api/src/utils/httpStatus.ts
  core-api/src/utils/messages.ts
  core-api/src/utils/serverError.ts
Labels: entity, feature, migration

#10 [CORE-API] Create Permission entity, Permission route, controller and service
  core-api/ormconfig.json
  core-api/src/app.ts
  core-api/src/controllers/permission.controller.ts
  core-api/src/database/migration/1560294968562-PermissionEntity.ts
  core-api/src/entities/permission.entity.ts
  core-api/src/routes/permission.route.ts
  core-api/src/services/permission.service.ts
  core-api/src/utils/httpStatus.ts
  core-api/src/utils/messages.ts
Labels: entity, feature, migration

#13 [CORE-API] Create PlaceCategory entity, route, controller and service
  core-api/src/app.ts
  core-api/src/controllers/placeCategory.controller.ts
  core-api/src/database/migration/1560547476933-PlaceCategoryEntity.ts
  core-api/src/entities/placeCategory.entity.ts
  core-api/src/routes/placeCategory.route.ts
  core-api/src/services/placeCategory.service.ts
  core-api/src/utils/messages.ts
Labels: entity, feature, migration

#16 [CORE-API] Create Place entity, route, controller and service #9
  core-api/src/app.ts
  core-api/src/controllers/place.controller.ts
  core-api/src/database/migration/1560547476933-PlaceCategoryEntity.ts
  core-api/src/database/migration/1560633068066-PlaceAndCategoryEntity.ts
  core-api/src/entities/place.entity.ts
  core-api/src/entities/placeCategory.entity.ts
  core-api/src/routes/place.route.ts
  core-api/src/services/place.service.ts
  core-api/src/services/placeCategory.service.ts
  core-api/src/utils/messages.ts
Labels: entity, feature, migration

#17 [CORE-API] Add Meal Entity, controller and service
  core-api/src/app.ts
  core-api/src/controllers/meal.controller.ts
  core-api/src/controllers/place.controller.ts
  core-api/src/database/migration/1560694527392-MealEntity.ts
  core-api/src/entities/meal.entity.ts
  core-api/src/entities/place.entity.ts
  core-api/src/entities/placeCategory.entity.ts
  core-api/src/routes/meal.route.ts
  core-api/src/routes/place.route.ts
  core-api/src/services/meal.service.ts
  core-api/src/services/place.service.ts
  core-api/src/services/placeCategory.service.ts
  core-api/src/utils/messages.ts
Labels: entity, feature, migration

#27 [CORE-API] Fix ts-node-dev: not found bug #14
  docker-compose.yml
Labels: bug, infra

#31 Change .travis.yml for pointing to master branch
  .travis.yml
Labels: bug, infra

#26 [ORDER] Create docker and folder structure for order service
  .gitignore
  core-api/src/config/database.ts
  docker-compose.yml
  order-service/.dockerignore
  order-service/Dockerfile
  order-service/ormconfig.js
  order-service/package.json
  order-service/src/app.ts
  order-service/src/config/database.ts
  order-service/tsconfig.json
Labels: feature, infra

#38 [ORDER-SERVICE] Create Order Entity, Controller, Service and Route
  docker-compose.yml
  order-service/package-lock.json
  order-service/package.json
  order-service/src/app.ts
  order-service/src/controllers/order.controller.ts
  order-service/src/database/migration/1561296131283-OrderEntity.ts
  order-service/src/entities/order.entity.ts
  order-service/src/routes/order.route.ts
  order-service/src/services/order.service.ts
  order-service/src/utils/Messages.ts
  order-service/src/utils/OrderStatus.ts
  order-service/src/utils/httpStatus.ts
  order-service/src/utils/serverError.ts
Labels: entity, feature, migration

#28 [CORE-API] Create CheckoutSlot entity, service, controller and routes
  core-api/src/app.ts
  core-api/src/controllers/checkoutSlot.controller.ts
  core-api/src/controllers/place.controller.ts
  core-api/src/database/migration/1560693487236-CheckoutSlotEntity.ts
  core-api/src/entities/checkoutSlot.entity.ts
  core-api/src/entities/place.entity.ts
  core-api/src/routes/checkoutSlot.route.ts
  core-api/src/routes/place.route.ts
  core-api/src/services/checkoutSlot.service.ts
  core-api/src/services/place.service.ts
  core-api/src/utils/messages.ts
  docker-compose.yml
Labels: entity, feature, migration

#18 [CORE-API] Add Access entity, relations, service and controller
  core-api/src/app.ts
  core-api/src/controllers/access.controller.ts
  core-api/src/database/migration/1561299410926-AccessEntity.ts
  core-api/src/entities/access.entity.ts
  core-api/src/entities/permission.entity.ts
  core-api/src/entities/place.entity.ts
  core-api/src/entities/user.entity.ts
  core-api/src/routes/access.route.ts
  core-api/src/services/access.service.ts
  core-api/src/services/permission.service.ts
  core-api/src/services/place.service.ts
  core-api/src/services/user.service.ts
  core-api/src/utils/messages.ts
Labels: entity, feature, migration

#25 Create docker and folder structure for preferences service
  .gitignore
  docker-compose.yml
  preferences-service/.dockerignore
  preferences-service/Dockerfile
  preferences-service/ormconfig.js
  preferences-service/package.json
  preferences-service/src/app.ts
  preferences-service/src/config/database.ts
  preferences-service/tsconfig.json
Labels: feature, infra

#41 [PREFERENCE-SERVICE] Create Preference Entity, Service, Controller an…
  .gitignore
  docker-compose.yml
  order-service/src/services/order.service.ts
  preference-service/.dockerignore
  preference-service/Dockerfile
  preference-service/ormconfig.js
  preference-service/package-lock.json
  preference-service/package.json
  preference-service/src/app.ts
  preference-service/src/config/database.ts
  preference-service/src/controllers/preference.controller.ts
  preference-service/src/database/migration/1561319684099-PreferenceEntity.ts
  preference-service/src/entities/preference.entity.ts
  preference-service/src/routes/preference.route.ts
  preference-service/src/services/preference.service.ts
  preference-service/src/utils/Messages.ts
  preference-service/src/utils/httpStatus.ts
  preference-service/src/utils/serverError.ts
  preference-service/tsconfig.json
Labels: entity, feature, migration

#45 [ORDER-SERVICE] Create OrderItem entity and status update logic
  order-service/src/controllers/order.controller.ts
  order-service/src/database/migration/1561396618110-OrderItems.ts
  order-service/src/entities/order.entity.ts
  order-service/src/entities/orderItem.entity.ts
  order-service/src/routes/order.route.ts
  order-service/src/services/order.service.ts
  order-service/src/utils/Messages.ts
  order-service/src/utils/OrderStatus.ts
  order-service/tsconfig.json
Labels: entity, feature, migration

#24 [NOTIFICATION] Create docker and folder structure for notification service
  docker-compose.yml
  notification-service/.dockerignore
  notification-service/Dockerfile
  notification-service/ormconfig.json
  notification-service/package-lock.json
  notification-service/package.json
  notification-service/src/app.ts
  notification-service/src/config/database.ts
  notification-service/src/controllers/notification.controller.ts
  notification-service/src/database/migration/1561412661461-NotificationEntity.ts
  notification-service/src/entities/notification.entity.ts
  notification-service/src/routes/notification.route.ts
  notification-service/src/services/notification.service.ts
  notification-service/src/utils/Messages.ts
  notification-service/src/utils/httpStatus.ts
  notification-service/src/utils/serverError.ts
  notification-service/tsconfig.json
Labels: feature, infra

#50 [ORDER-SERVICE] Integrate Order with NotificationService #49
  order-service/package-lock.json
  order-service/package.json
  order-service/src/services/notification.service.ts
  order-service/src/services/order.service.ts
Labels: feature, infra

#48 [CORE-API] Integrate CoreAPI with PreferenceService
  core-api/package-lock.json
  core-api/package.json
  core-api/src/app.ts
  core-api/src/controllers/preference.controller.ts
  core-api/src/routes/preference.route.ts
  core-api/src/services/preference.service.ts
  core-api/tsconfig.json
Labels: feature, infra

#52 [CORE-API] Integrate CoreAPI with NotificationService #46
  core-api/src/app.ts
  core-api/src/controllers/notification.controller.ts
  core-api/src/routes/notification.route.ts
  core-api/src/services/notification.service.ts
Labels: feature, infra

#51 Add swagger and integrate with user route
  core-api/package.json
  core-api/src/app.ts
  core-api/src/controllers/meal.controller.ts
  core-api/src/controllers/place.controller.ts
  core-api/src/entities/access.entity.ts
  core-api/src/entities/meal.entity.ts
  core-api/src/entities/place.entity.ts
  core-api/src/routes/access.route.ts
  core-api/src/routes/auth.route.ts
  core-api/src/routes/checkoutSlot.route.ts
  core-api/src/routes/meal.route.ts
  core-api/src/routes/notification.route.ts
  core-api/src/routes/order.route.ts
  core-api/src/routes/permission.route.ts
  core-api/src/routes/place.route.ts
  core-api/src/routes/placeCategory.route.ts
  core-api/src/routes/preference.route.ts
  core-api/src/routes/user.route.ts
  core-api/src/services/meal.service.ts
  core-api/src/services/place.service.ts
  core-api/src/utils/messages.ts
  init.sh
Labels: feature, infra

#55 Add run migrations on init.sh
  run_migrations.sh
Labels: infra

#56 Update README.md
  GQM.md
  README.md
Labels: enhancement
